### ISSUE TITLE
displaying taxonomy meta

### ISSUE THREAD

**Issue by sb-lc** [jtsternberg/Taxonomy_MetaData#17]
$taxonomy = 'category';
$term_id = 3;
Taxonomy_MetaData::get( $taxonomy, $term_id );

how do I use the data stored in Taxonomy_MetaData as shown above?

thanks

**Comment by sb-lc** [comment]
i am using cmb2 btw

**Comment by jtsternberg** [comment]
[Answer provided here](https://github.com/jtsternberg/Taxonomy_MetaData/issues/2#issuecomment-68921647).
