### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by sb-lc** [jtsternberg/Taxonomy_MetaData#18]
I am about to uninstall this script as I have spent 12 hours trying everything I can think of to get it to work with no joy. the support is not there on this forum, peoples questions are unanswered so I am assuming it is broken and will be removed from github in due time.

**Comment by jtsternberg** [comment]
A) this is not an issue, B), this is not a support forum, C) Support is not offered or guaranteed, but occasionally provided as time permits, and D) this script is provided free of charge.

I apologize for your struggles, but please keep these considerations in mind next time you're tempted to open a passive-aggressive issue like this.
